### ISSUE TITLE
Fix post actions numbers

### ISSUE THREAD

**Issue by Dennull** [Project-Chirp/chirp-frontend#29]
STEPS:

1. Go to any post
2. Like or unlike the post

OBSERVED:

- Sometimes all of the other icons in the post actions area will shift over when the number of likes changes

EXPECTED:

- The number of likes changing shouldn't affect the other icons in the post actions area

**Comment by AnindaS13** [comment]
I added a position property with value of absolute to actionitems style in PostItem.tsx. Changed padding since that made the numbers misplace and don't see the issue anymore. The branch is linked to this ticket.

**Comment by Dennull** [comment]
Nice, can you make a PR once it's ready?
